name: Build an image with the signature

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: raster0x2a
          password: ${{ github.token }}

      - name: install cosign
        uses: sigstore/cosign-installer@main

      - name: Prepare Dockerfile
        run: |
          echo "FROM alpine:3.10" > Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: |
            ghcr.io/raster0x2a/test-image:latest
          platforms: linux/amd64
          push: true

      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --force ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}

      - name: Verify the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign verify ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}
    
    permissions:
      packages: write
      id-token: write
